name: CI

on:
  push:
    branches: 
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  client:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env: 
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run tsc

  deploy:
    needs: [client, server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "vaccine-exercise-tn"
          heroku_email: "toni.naumis@gmail.com"
          healthcheck: "https://vaccine-exercise-tn.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
